version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./bdd/populate.sql:/docker-entrypoint-initdb.d/populate.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: software
      POSTGRES_USER: software
      POSTGRES_DB: software

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    hostname: localhost
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: software
      DATABASE_PASSWORD: software
      DATABASE_NAME: software

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api