version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/populate.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: software
      POSTGRES_USER: software
      POSTGRES_DB: software